version: '3.6'

services:

  # Backend API
  navbar-service:
    container_name: rewards-api
    build: ./
    command: |
      yarn build
      yarn start
    working_dir: /app
    ports:
      - "3006:3006"


